/**
 * Build script — 把 chat webview 运行时 bundle 注入 template.html,
 * 输出 TS 字符串模块 chatHtml.generated.ts(进 Metro JS 包,热更新生效,
 * 无需重建 APK)。与 build-reader.js 同构(esbuild + split/join 注入)。
 *
 * Run: node scripts/build-chat.js
 */
const esbuild = require("esbuild");
const fs = require("node:fs");
const path = require("node:path");

const WEBVIEW_DIR = path.resolve(__dirname, "../src/lib/chat/webview");
const TEMPLATE = path.resolve(WEBVIEW_DIR, "template.html");
const ENTRY = path.resolve(WEBVIEW_DIR, "index.ts");
const OUTPUT = path.resolve(__dirname, "../src/lib/chat/chatHtml.generated.ts");
const MARKER = "<!-- __CHAT_BUNDLE_INSERT_9c2e1f__ -->";

async function buildChat() {
  const result = await esbuild.build({
    entryPoints: [ENTRY],
    bundle: true,
    format: "iife",
    target: "es2020",
    // dev 迭代期不 minify:webview 报错带真实行号,便于定位;发布构建 CHAT_MINIFY=1
    minify: process.env.CHAT_MINIFY === "1",
    write: false,
    define: {
      __CHAT_BUILD_ID__: JSON.stringify(
        process.env.CHAT_BUILD_ID || new Date().toISOString().slice(0, 16).replace(/[-T:]/g, ""),
      ),
    },
  });

  const bundledJS = result.outputFiles[0].text;
  const template = fs.readFileSync(TEMPLATE, "utf-8");

  // split/join 而非 replace,避免 JS 里的 $ 替换序列
  const parts = template.split(MARKER);
  if (parts.length !== 2) {
    console.error(`Marker not found (or duplicated) in template: ${MARKER}`);
    process.exit(1);
  }
  const html = `${parts[0]}<script>\n${bundledJS}\n</script>${parts[1]}`;

  // U+2028/U+2029:JSON 合法但 JS 字面量中(旧引擎)非法,显式转义为 \uXXXX 序列
  // 注意:JSON.stringify 已处理全部引号/换行;HTML 标签原样保留(字符串嵌入 TS 模块)
  const tsSource =
    `// GENERATED by scripts/build-chat.js — DO NOT EDIT.\n` +
    `// built at ${new Date().toISOString()}\n` +
    `export const CHAT_HTML = ${JSON.stringify(html)
      .replace(/\u2028/g, "\\u2028")
      .replace(/\u2029/g, "\\u2029")};\n`;

  fs.writeFileSync(OUTPUT, tsSource, "utf-8");
  console.log(
    `Built chatHtml.generated.ts (html ${Math.round(html.length / 1024)}KB, bundle ${Math.round(
      bundledJS.length / 1024,
    )}KB)`,
  );
}

buildChat().catch((err) => {
  console.error("Build failed:", err);
  process.exit(1);
});
