/**
 * Z-Library 支持语言全表(源自 koplugin v1.0.49 SUPPORTED_LANGUAGES,185 项,已剔除内联的高频 6 项)。
 * 由插件源码提取生成(2026-09-11);值是 ZL API 的小写英文名。
 */
export const ZL_MORE_LANGUAGES: { value: string; label: string }[] = [
  { value: "abkhazian", label: "Abkhazian" },
  { value: "afar", label: "Afar" },
  { value: "afrikaans", label: "Afrikaans" },
  { value: "akan", label: "Akan" },
  { value: "albanian", label: "Albanian" },
  { value: "amharic", label: "Amharic" },
  { value: "arabic", label: "العربية" },
  { value: "aragonese", label: "Aragonese" },
  { value: "armenian", label: "Հայերեն" },
  { value: "assamese", label: "Assamese" },
  { value: "avaric", label: "Avaric" },
  { value: "avestan", label: "Avestan" },
  { value: "aymara", label: "Aymara" },
  { value: "azerbaijani", label: "Azərbaycanca" },
  { value: "bambara", label: "Bambara" },
  { value: "bashkir", label: "Bashkir" },
  { value: "basque", label: "Basque" },
  { value: "belarusian", label: "Belarusian" },
  { value: "bengali", label: "বাংলা" },
  { value: "berber", label: "Berber" },
  { value: "bislama", label: "Bislama" },
  { value: "bosnian", label: "Bosnian" },
  { value: "brazilian", label: "Brazilian Portuguese" },
  { value: "breton", label: "Breton" },
  { value: "bulgarian", label: "Bulgarian" },
  { value: "burmese", label: "Burmese" },
  { value: "catalan", label: "Catalan" },
  { value: "central_khmer", label: "Central Khmer" },
  { value: "chamorro", label: "Chamorro" },
  { value: "chechen", label: "Chechen" },
  { value: "chichewa", label: "Chichewa" },
  { value: "church_slavic", label: "Church Slavic" },
  { value: "chuvash", label: "Chuvash" },
  { value: "cornish", label: "Cornish" },
  { value: "corsican", label: "Corsican" },
  { value: "cree", label: "Cree" },
  { value: "crimean", label: "Crimean Tatar" },
  { value: "croatian", label: "Croatian" },
  { value: "czech", label: "Czech" },
  { value: "danish", label: "Danish" },
  { value: "divehi", label: "Divehi" },
  { value: "dutch", label: "Nederlands" },
  { value: "dzongkha", label: "Dzongkha" },
  { value: "esperanto", label: "Esperanto" },
  { value: "estonian", label: "Estonian" },
  { value: "ewe", label: "Ewe" },
  { value: "faroese", label: "Faroese" },
  { value: "fijian", label: "Fijian" },
  { value: "finnish", label: "Finnish" },
  { value: "fulah", label: "Fulah" },
  { value: "gaelic", label: "Gaelic" },
  { value: "galician", label: "Galician" },
  { value: "ganda", label: "Ganda" },
  { value: "georgian", label: "ქართული" },
  { value: "greek", label: "Ελληνικά" },
  { value: "guarani", label: "Guarani" },
  { value: "gujarati", label: "Gujarati" },
  { value: "haitian", label: "Haitian" },
  { value: "hausa", label: "Hausa" },
  { value: "hebrew", label: "Hebrew" },
  { value: "herero", label: "Herero" },
  { value: "hindi", label: "हिन्दी" },
  { value: "hiri_motu", label: "Hiri Motu" },
  { value: "hungarian", label: "Hungarian" },
  { value: "icelandic", label: "Icelandic" },
  { value: "ido", label: "Ido" },
  { value: "igbo", label: "Igbo" },
  { value: "indigenous", label: "Indigenous" },
  { value: "indonesian", label: "Bahasa Indonesia" },
  { value: "interlingua", label: "Interlingua" },
  { value: "inuktitut", label: "Inuktitut" },
  { value: "inupiaq", label: "Inupiaq" },
  { value: "irish", label: "Irish" },
  { value: "italian", label: "Italiano" },
  { value: "japanese", label: "日本語" },
  { value: "javanese", label: "Javanese" },
  { value: "kalaallisut", label: "Kalaallisut" },
  { value: "kannada", label: "Kannada" },
  { value: "kanuri", label: "Kanuri" },
  { value: "karakalpak", label: "Karakalpak" },
  { value: "kashmiri", label: "Kashmiri" },
  { value: "kazakh", label: "Kazakh" },
  { value: "kikuyu", label: "Kikuyu" },
  { value: "kinyarwanda", label: "Kinyarwanda" },
  { value: "kyrgyz", label: "Kirghiz" },
  { value: "komi", label: "Komi" },
  { value: "kongo", label: "Kongo" },
  { value: "korean", label: "한국어" },
  { value: "kuanyama", label: "Kuanyama" },
  { value: "kurdish", label: "Kurdish" },
  { value: "lao", label: "Lao" },
  { value: "latin", label: "Latin" },
  { value: "latvian", label: "Latvian" },
  { value: "limburgan", label: "Limburgan" },
  { value: "lingala", label: "Lingala" },
  { value: "lithuanian", label: "Lithuanian" },
  { value: "luba-katanga", label: "Luba-Katanga" },
  { value: "luxembourgish", label: "Luxembourgish" },
  { value: "macedonian", label: "Macedonian" },
  { value: "malagasy", label: "Malagasy" },
  { value: "malayalam", label: "Malayalam" },
  { value: "malaysian", label: "Bahasa Malaysia" },
  { value: "maltese", label: "Maltese" },
  { value: "manx", label: "Manx" },
  { value: "maori", label: "Maori" },
  { value: "marathi", label: "Marathi" },
  { value: "marshallese", label: "Marshallese" },
  { value: "moldavian", label: "Moldavian" },
  { value: "mongolian", label: "Mongolian" },
  { value: "nauru", label: "Nauru" },
  { value: "navajo", label: "Navajo" },
  { value: "ndonga", label: "Ndonga" },
  { value: "nepali", label: "Nepali" },
  { value: "north_ndebele", label: "North Ndebele" },
  { value: "northern_sami", label: "Northern Sami" },
  { value: "norwegian", label: "Norwegian" },
  { value: "norwegian_bokmal", label: "Norwegian Bokmål" },
  { value: "norwegian_nynorsk", label: "Norwegian Nynorsk" },
  { value: "occidental", label: "Occidental" },
  { value: "occitan", label: "Occitan" },
  { value: "odia", label: "Odia" },
  { value: "ojibwa", label: "Ojibwa" },
  { value: "oromo", label: "Oromo" },
  { value: "ossetian", label: "Ossetian" },
  { value: "pali", label: "Pali" },
  { value: "pashto", label: "پښتو" },
  { value: "persian", label: "Persian" },
  { value: "polish", label: "Polski" },
  { value: "portuguese", label: "Português" },
  { value: "punjabi", label: "Punjabi" },
  { value: "quechua", label: "Quechua" },
  { value: "romanian", label: "Romanian" },
  { value: "romansh", label: "Romansh" },
  { value: "rundi", label: "Rundi" },
  { value: "samoan", label: "Samoan" },
  { value: "sango", label: "Sango" },
  { value: "sanskrit", label: "Sanskrit" },
  { value: "sardinian", label: "Sardinian" },
  { value: "serbian", label: "Српски" },
  { value: "shona", label: "Shona" },
  { value: "sichuan_yi", label: "Sichuan Yi" },
  { value: "sindhi", label: "Sindhi" },
  { value: "sinhala", label: "Sinhala" },
  { value: "slovak", label: "Slovak" },
  { value: "slovenian", label: "Slovenian" },
  { value: "somali", label: "Somali" },
  { value: "south_ndebele", label: "South Ndebele" },
  { value: "southern_sotho", label: "Southern Sotho" },
  { value: "sundanese", label: "Sundanese" },
  { value: "swahili", label: "Swahili" },
  { value: "swati", label: "Swati" },
  { value: "swedish", label: "Swedish" },
  { value: "tagalog", label: "Tagalog (Filipino)" },
  { value: "tahitian", label: "Tahitian" },
  { value: "tajik", label: "Tajik" },
  { value: "tamil", label: "Tamil" },
  { value: "tatar", label: "Tatar" },
  { value: "telugu", label: "Telugu" },
  { value: "thai", label: "ไทย" },
  { value: "tibetan", label: "Tibetan" },
  { value: "tigrinya", label: "Tigrinya" },
  { value: "tonga", label: "Tonga" },
  { value: "traditional chinese", label: "繁體中文" },
  { value: "tsonga", label: "Tsonga" },
  { value: "tswana", label: "Tswana" },
  { value: "turkish", label: "Türkçe" },
  { value: "turkmen", label: "Turkmen" },
  { value: "twi", label: "Twi" },
  { value: "uighur", label: "Uighur" },
  { value: "ukrainian", label: "Українська" },
  { value: "urdu", label: "اردو" },
  { value: "uzbek", label: "Uzbek" },
  { value: "venda", label: "Venda" },
  { value: "vietnamese", label: "Tiếng Việt" },
  { value: "volapuk", label: "Volapük" },
  { value: "walloon", label: "Walloon" },
  { value: "welsh", label: "Welsh" },
  { value: "western_frisian", label: "Western Frisian" },
  { value: "wolof", label: "Wolof" },
  { value: "xhosa", label: "Xhosa" },
  { value: "yakut", label: "Yakut" },
  { value: "yiddish", label: "Yiddish" },
  { value: "yoruba", label: "Yoruba" },
  { value: "zhuang", label: "Zhuang" },
  { value: "zulu", label: "Zulu" },
];
